### ISSUE TITLE
Rolling Scope School 2018-Q1 code wars

### ISSUE THREAD

**Issue by forkollaider** [rolling-scopes/karate#39]
If you have issues with your codewars score please leave a comment by form:
1) codewars login
2) current score
3) expected score

**Comment by verus774** [comment]
verus774
92
100
____
fixed

**Comment by pinkrefugee** [comment]
pinkrefugee
undefined
100
_____
fixed

**Comment by artyom123** [comment]
artyom123
undefined
100

**Comment by kakoc** [comment]
1. koc_kakoc
2. 135
3. 100 + 10 + 15 + 20 = 145

**Comment by anton-yatskevich** [comment]
anton-yatskevich
104
115

**Comment by Srjkaa** [comment]
1. srjkaa-
2. 120
3. 140

**Comment by EugeneLitvinchuk** [comment]
1. morzh1205
2. 95
3. 105

**Comment by Anton-Koniouchevsky** [comment]
1. Anton-Koniouchevsky
2. undefined
3. 145

**Comment by yanyan155** [comment]
1. yanyan155
2. undefined
3. 105

**Comment by anton-yatskevich** [comment]
anton-yatskevich
104
125

**Comment by AntonAtrashkou** [comment]
AntonAtrashkou

**Comment by AntonAtrashkou** [comment]
AntonAtrashkou
71
105

**Comment by poulkud** [comment]
1. gambit670
2. undefined
3. 44

**Comment by godofnoobs** [comment]
1. godofnoobs
2. 136
3. 145

**Comment by uladzimir-yeudakimovich** [comment]
87 ?

**Comment by Srjkaa** [comment]
Так как ката, которая ранее была 3 kuy теперь имеет 5 kuy, говорю я об этой задаче - http://www.codewars.com/kata/can-you-get-the-loop, значит теперь максимум не 145, а 135 баллов, тем не менее, у меня не была решена только одна ката на 5 баллов и с нынешними макс. баллами должно быть 130, если конечно максимум 135. До того как оставил пост здесь ранее было 120 баллов, теперь 119, в чём прикол?)

**Comment by artyom123** [comment]
artyom123
66
100

**Comment by dmitry-nistratov** [comment]
dmitry-nistratov
undefined
100

**Comment by KirylNik** [comment]
KiryllNik
106
110

**Comment by klayder** [comment]
1. klayder https://www.codewars.com/users/klayder
2. undefined
3. 115

**Comment by godofnoobs** [comment]
godofnoobs
    было 136 сейчас понизили до 116
    Уважаемые, все задачи решены, включая sql! Верните хоть что было.

**Comment by veranikashneidzer** [comment]
NikaNeider
Было 135
Стало 134

**Comment by yanaSelin** [comment]
yanaSelin
Все задачи решены, в скоре стояло 135
Сейчас стало 126

**Comment by Srjkaa** [comment]
Srjkaa
Решено на 130 (с учётом того, что бонусная ката can you get the loop стала 5 kuy)
Изначально стояло 120, потом 119, теперь вовсе 115

**Comment by Alexstraszza** [comment]
Alexstraszza
Сейчас 90
Было 100 (стояло изначально. потом заменилось на 90, но задач решено на сотку)

**Comment by forkollaider** [comment]
Прикол в том, что апи кодварса падает он наших запросов. В ближайщие дни(часы) запущу отдельно для всех, кому выставило неправильно

**Comment by MSt1ch** [comment]
MSt1ch
было 75 (корректно)
стало 41 (неправильный бал)

**Comment by oleg291291** [comment]
oleg291291
current = 73
before = 101 (as I remember)

**Comment by sergeybolzan** [comment]
1. sergeybolzan
2. было 110, стало 99
3. 110

**Comment by anatolhancharou** [comment]
1. Anatol_Hancharou
2. 82
3. 95

**Comment by MigalenkoVadim** [comment]
1) Arhiii
2) 81
3) 105

**Comment by dmi3q** [comment]
1. dmi3q
2. 99 (it was 105 before score update ~3 weeks ago)
3. 105
